/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Address,
  PaymentLinkResponse,
  ResultListOrder,
  ResultOrder,
  ResultOrderItem,
} from '../models/index';
import {
    AddressFromJSON,
    AddressToJSON,
    PaymentLinkResponseFromJSON,
    PaymentLinkResponseToJSON,
    ResultListOrderFromJSON,
    ResultListOrderToJSON,
    ResultOrderFromJSON,
    ResultOrderToJSON,
    ResultOrderItemFromJSON,
    ResultOrderItemToJSON,
} from '../models/index';

export interface CancelOrderRequest {
    orderId: number;
}

export interface CreateOrderRequest {
    paymentMethod: CreateOrderPaymentMethodEnum;
    address: Address;
}

export interface GetOrderByIdRequest {
    orderId: number;
}

export interface GetOrderItemByIdRequest {
    orderItemId: number;
}

/**
 * 
 */
export class OrderControllerApi extends runtime.BaseAPI {

    /**
     */
    async cancelOrderRaw(requestParameters: CancelOrderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResultOrder>> {
        if (requestParameters['orderId'] == null) {
            throw new runtime.RequiredError(
                'orderId',
                'Required parameter "orderId" was null or undefined when calling cancelOrder().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/orders/{orderId}/cancel`.replace(`{${"orderId"}}`, encodeURIComponent(String(requestParameters['orderId']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResultOrderFromJSON(jsonValue));
    }

    /**
     */
    async cancelOrder(requestParameters: CancelOrderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResultOrder> {
        const response = await this.cancelOrderRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async createOrderRaw(requestParameters: CreateOrderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PaymentLinkResponse>> {
        if (requestParameters['paymentMethod'] == null) {
            throw new runtime.RequiredError(
                'paymentMethod',
                'Required parameter "paymentMethod" was null or undefined when calling createOrder().'
            );
        }

        if (requestParameters['address'] == null) {
            throw new runtime.RequiredError(
                'address',
                'Required parameter "address" was null or undefined when calling createOrder().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['paymentMethod'] != null) {
            queryParameters['paymentMethod'] = requestParameters['paymentMethod'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/orders`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AddressToJSON(requestParameters['address']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PaymentLinkResponseFromJSON(jsonValue));
    }

    /**
     */
    async createOrder(requestParameters: CreateOrderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PaymentLinkResponse> {
        const response = await this.createOrderRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getOrderByIdRaw(requestParameters: GetOrderByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResultOrder>> {
        if (requestParameters['orderId'] == null) {
            throw new runtime.RequiredError(
                'orderId',
                'Required parameter "orderId" was null or undefined when calling getOrderById().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/orders/{orderId}`.replace(`{${"orderId"}}`, encodeURIComponent(String(requestParameters['orderId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResultOrderFromJSON(jsonValue));
    }

    /**
     */
    async getOrderById(requestParameters: GetOrderByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResultOrder> {
        const response = await this.getOrderByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getOrderItemByIdRaw(requestParameters: GetOrderItemByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResultOrderItem>> {
        if (requestParameters['orderItemId'] == null) {
            throw new runtime.RequiredError(
                'orderItemId',
                'Required parameter "orderItemId" was null or undefined when calling getOrderItemById().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/orders/item/{orderItemId}`.replace(`{${"orderItemId"}}`, encodeURIComponent(String(requestParameters['orderItemId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResultOrderItemFromJSON(jsonValue));
    }

    /**
     */
    async getOrderItemById(requestParameters: GetOrderItemByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResultOrderItem> {
        const response = await this.getOrderItemByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async usersOrderHistoryHandlersRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResultListOrder>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/orders/user`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResultListOrderFromJSON(jsonValue));
    }

    /**
     */
    async usersOrderHistoryHandlers(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResultListOrder> {
        const response = await this.usersOrderHistoryHandlersRaw(initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const CreateOrderPaymentMethodEnum = {
    Stripe: 'STRIPE',
    Paypal: 'PAYPAL'
} as const;
export type CreateOrderPaymentMethodEnum = typeof CreateOrderPaymentMethodEnum[keyof typeof CreateOrderPaymentMethodEnum];
