/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ResultListOrder,
  ResultOrder,
} from '../models/index';
import {
    ResultListOrderFromJSON,
    ResultListOrderToJSON,
    ResultOrderFromJSON,
    ResultOrderToJSON,
} from '../models/index';

export interface UpdateOrderStatusRequest {
    orderId: number;
    orderStatus: UpdateOrderStatusOrderStatusEnum;
}

/**
 * 
 */
export class SellerOrderControllerApi extends runtime.BaseAPI {

    /**
     */
    async getAllOrdersRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResultListOrder>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/seller/order`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResultListOrderFromJSON(jsonValue));
    }

    /**
     */
    async getAllOrders(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResultListOrder> {
        const response = await this.getAllOrdersRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async updateOrderStatusRaw(requestParameters: UpdateOrderStatusRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResultOrder>> {
        if (requestParameters['orderId'] == null) {
            throw new runtime.RequiredError(
                'orderId',
                'Required parameter "orderId" was null or undefined when calling updateOrderStatus().'
            );
        }

        if (requestParameters['orderStatus'] == null) {
            throw new runtime.RequiredError(
                'orderStatus',
                'Required parameter "orderStatus" was null or undefined when calling updateOrderStatus().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/seller/order/{orderId}/status/{orderStatus}`.replace(`{${"orderId"}}`, encodeURIComponent(String(requestParameters['orderId']))).replace(`{${"orderStatus"}}`, encodeURIComponent(String(requestParameters['orderStatus']))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResultOrderFromJSON(jsonValue));
    }

    /**
     */
    async updateOrderStatus(requestParameters: UpdateOrderStatusRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResultOrder> {
        const response = await this.updateOrderStatusRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const UpdateOrderStatusOrderStatusEnum = {
    Pending: 'PENDING',
    Placed: 'PLACED',
    Confirmed: 'CONFIRMED',
    Shipped: 'SHIPPED',
    Delivered: 'DELIVERED',
    Cancelled: 'CANCELLED'
} as const;
export type UpdateOrderStatusOrderStatusEnum = typeof UpdateOrderStatusOrderStatusEnum[keyof typeof UpdateOrderStatusOrderStatusEnum];
