/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ResultWishlist,
} from '../models/index';
import {
    ResultWishlistFromJSON,
    ResultWishlistToJSON,
} from '../models/index';

export interface AddProductToWishListRequest {
    productId: number;
}

/**
 * 
 */
export class WishlistControllerApi extends runtime.BaseAPI {

    /**
     */
    async addProductToWishListRaw(requestParameters: AddProductToWishListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResultWishlist>> {
        if (requestParameters['productId'] == null) {
            throw new runtime.RequiredError(
                'productId',
                'Required parameter "productId" was null or undefined when calling addProductToWishList().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/wishlist/add-product/{productId}`.replace(`{${"productId"}}`, encodeURIComponent(String(requestParameters['productId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResultWishlistFromJSON(jsonValue));
    }

    /**
     */
    async addProductToWishList(requestParameters: AddProductToWishListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResultWishlist> {
        const response = await this.addProductToWishListRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async createWishlistRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResultWishlist>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/wishlist/create`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResultWishlistFromJSON(jsonValue));
    }

    /**
     */
    async createWishlist(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResultWishlist> {
        const response = await this.createWishlistRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async getWishlistByUserIdRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResultWishlist>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/wishlist`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResultWishlistFromJSON(jsonValue));
    }

    /**
     */
    async getWishlistByUserId(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResultWishlist> {
        const response = await this.getWishlistByUserIdRaw(initOverrides);
        return await response.value();
    }

}
