/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface AddAddressRequestDTO
 */
export interface AddAddressRequestDTO {
    /**
     * 
     * @type {string}
     * @memberof AddAddressRequestDTO
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof AddAddressRequestDTO
     */
    'street': string;
    /**
     * 
     * @type {string}
     * @memberof AddAddressRequestDTO
     */
    'locality'?: string;
    /**
     * 
     * @type {string}
     * @memberof AddAddressRequestDTO
     */
    'zip': string;
    /**
     * 
     * @type {string}
     * @memberof AddAddressRequestDTO
     */
    'city': string;
    /**
     * 
     * @type {string}
     * @memberof AddAddressRequestDTO
     */
    'country': string;
    /**
     * 
     * @type {string}
     * @memberof AddAddressRequestDTO
     */
    'mobile'?: string;
}

