/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface AddressDtoResponse
 */
export interface AddressDtoResponse {
    /**
     * 
     * @type {number}
     * @memberof AddressDtoResponse
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof AddressDtoResponse
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof AddressDtoResponse
     */
    'street'?: string;
    /**
     * 
     * @type {string}
     * @memberof AddressDtoResponse
     */
    'locality'?: string;
    /**
     * 
     * @type {string}
     * @memberof AddressDtoResponse
     */
    'zip'?: string;
    /**
     * 
     * @type {string}
     * @memberof AddressDtoResponse
     */
    'city'?: string;
    /**
     * 
     * @type {string}
     * @memberof AddressDtoResponse
     */
    'country'?: string;
    /**
     * 
     * @type {string}
     * @memberof AddressDtoResponse
     */
    'mobile'?: string;
    /**
     * 
     * @type {number}
     * @memberof AddressDtoResponse
     */
    'order_id'?: number;
    /**
     * 
     * @type {number}
     * @memberof AddressDtoResponse
     */
    'seller_id'?: number;
    /**
     * 
     * @type {number}
     * @memberof AddressDtoResponse
     */
    'user_id'?: number;
}

