/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface BusinessDetails
 */
export interface BusinessDetails {
    /**
     * 
     * @type {string}
     * @memberof BusinessDetails
     */
    'businessName'?: string;
    /**
     * 
     * @type {string}
     * @memberof BusinessDetails
     */
    'businessAddress'?: string;
    /**
     * 
     * @type {string}
     * @memberof BusinessDetails
     */
    'businessEmail'?: string;
    /**
     * 
     * @type {string}
     * @memberof BusinessDetails
     */
    'businessMobile'?: string;
    /**
     * 
     * @type {string}
     * @memberof BusinessDetails
     */
    'logo'?: string;
    /**
     * 
     * @type {string}
     * @memberof BusinessDetails
     */
    'banner'?: string;
}

