/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CartItemQuantityUpdateReq
 */
export interface CartItemQuantityUpdateReq {
    /**
     * 
     * @type {number}
     * @memberof CartItemQuantityUpdateReq
     */
    cartItemId?: number;
    /**
     * 
     * @type {number}
     * @memberof CartItemQuantityUpdateReq
     */
    quantity?: number;
}

/**
 * Check if a given object implements the CartItemQuantityUpdateReq interface.
 */
export function instanceOfCartItemQuantityUpdateReq(value: object): value is CartItemQuantityUpdateReq {
    return true;
}

export function CartItemQuantityUpdateReqFromJSON(json: any): CartItemQuantityUpdateReq {
    return CartItemQuantityUpdateReqFromJSONTyped(json, false);
}

export function CartItemQuantityUpdateReqFromJSONTyped(json: any, ignoreDiscriminator: boolean): CartItemQuantityUpdateReq {
    if (json == null) {
        return json;
    }
    return {
        
        'cartItemId': json['cartItemId'] == null ? undefined : json['cartItemId'],
        'quantity': json['quantity'] == null ? undefined : json['quantity'],
    };
}

  export function CartItemQuantityUpdateReqToJSON(json: any): CartItemQuantityUpdateReq {
      return CartItemQuantityUpdateReqToJSONTyped(json, false);
  }

  export function CartItemQuantityUpdateReqToJSONTyped(value?: CartItemQuantityUpdateReq | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'cartItemId': value['cartItemId'],
        'quantity': value['quantity'],
    };
}

