/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { User } from './user';

/**
 * 
 * @export
 * @interface Coupon
 */
export interface Coupon {
    /**
     * 
     * @type {number}
     * @memberof Coupon
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof Coupon
     */
    'code'?: string;
    /**
     * 
     * @type {number}
     * @memberof Coupon
     */
    'discountPercentage'?: number;
    /**
     * 
     * @type {string}
     * @memberof Coupon
     */
    'validityStartDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof Coupon
     */
    'validityEndDate'?: string;
    /**
     * 
     * @type {number}
     * @memberof Coupon
     */
    'minimumOrderValue'?: number;
    /**
     * 
     * @type {Set<User>}
     * @memberof Coupon
     */
    'usedByUsers'?: Set<User>;
    /**
     * 
     * @type {boolean}
     * @memberof Coupon
     */
    'active'?: boolean;
}

