/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface CreateProductReq
 */
export interface CreateProductReq {
  /**
   *
   * @type {string}
   * @memberof CreateProductReq
   */
  title?: string;
  /**
   *
   * @type {string}
   * @memberof CreateProductReq
   */
  description?: string;
  /**
   *
   * @type {number}
   * @memberof CreateProductReq
   */
  maxPrice?: number;
  /**
   *
   * @type {number}
   * @memberof CreateProductReq
   */
  sellingPrice?: number;
  /**
   *
   * @type {string}
   * @memberof CreateProductReq
   */
  color?: string;
  /**
   *
   * @type {Array<string>}
   * @memberof CreateProductReq
   */
  images?: Array<string>;
  /**
   *
   * @type {string}
   * @memberof CreateProductReq
   */
  category?: string;
  /**
   *
   * @type {string}
   * @memberof CreateProductReq
   */
  category2?: string;
  /**
   *
   * @type {string}
   * @memberof CreateProductReq
   */
  category3?: string;
  /**
   *
   * @type {string}
   * @memberof CreateProductReq
   */
  sizes?: string;
}

