/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Deal } from './deal';
// May contain unused imports in some cases
// @ts-ignore
import type { HomeCategory } from './home-category';

/**
 * 
 * @export
 * @interface Home
 */
export interface Home {
    /**
     * 
     * @type {Array<HomeCategory>}
     * @memberof Home
     */
    'grid'?: Array<HomeCategory>;
    /**
     * 
     * @type {Array<HomeCategory>}
     * @memberof Home
     */
    'shopByCategories'?: Array<HomeCategory>;
    /**
     * 
     * @type {Array<HomeCategory>}
     * @memberof Home
     */
    'electricCategories'?: Array<HomeCategory>;
    /**
     * 
     * @type {Array<HomeCategory>}
     * @memberof Home
     */
    'dealCategories'?: Array<HomeCategory>;
    /**
     * 
     * @type {Array<Deal>}
     * @memberof Home
     */
    'deals'?: Array<Deal>;
}

