/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Product } from './product';

/**
 * 
 * @export
 * @interface OrderItem
 */
export interface OrderItem {
    /**
     * 
     * @type {number}
     * @memberof OrderItem
     */
    'id'?: number;
    /**
     * 
     * @type {Product}
     * @memberof OrderItem
     */
    'product'?: Product;
    /**
     * 
     * @type {string}
     * @memberof OrderItem
     */
    'size'?: string;
    /**
     * 
     * @type {number}
     * @memberof OrderItem
     */
    'quantity'?: number;
    /**
     * 
     * @type {number}
     * @memberof OrderItem
     */
    'mrpPrice'?: number;
    /**
     * 
     * @type {number}
     * @memberof OrderItem
     */
    'sellingPrice'?: number;
    /**
     * 
     * @type {number}
     * @memberof OrderItem
     */
    'userId'?: number;
}

