/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PaymentDetails
 */
export interface PaymentDetails {
    /**
     * 
     * @type {string}
     * @memberof PaymentDetails
     */
    paymentId?: string;
    /**
     * 
     * @type {string}
     * @memberof PaymentDetails
     */
    paymentLinkId?: string;
    /**
     * 
     * @type {string}
     * @memberof PaymentDetails
     */
    paymentLinkReferenceId?: string;
    /**
     * 
     * @type {string}
     * @memberof PaymentDetails
     */
    paymentLinkStatus?: string;
    /**
     * 
     * @type {string}
     * @memberof PaymentDetails
     */
    paymentIdZWSP?: string;
    /**
     * 
     * @type {string}
     * @memberof PaymentDetails
     */
    status?: PaymentDetailsStatusEnum;
}


/**
 * @export
 */
export const PaymentDetailsStatusEnum = {
    Pending: 'PENDING',
    Processing: 'PROCESSING',
    Completed: 'COMPLETED',
    Failed: 'FAILED'
} as const;
export type PaymentDetailsStatusEnum = typeof PaymentDetailsStatusEnum[keyof typeof PaymentDetailsStatusEnum];


/**
 * Check if a given object implements the PaymentDetails interface.
 */
export function instanceOfPaymentDetails(value: object): value is PaymentDetails {
    return true;
}

export function PaymentDetailsFromJSON(json: any): PaymentDetails {
    return PaymentDetailsFromJSONTyped(json, false);
}

export function PaymentDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaymentDetails {
    if (json == null) {
        return json;
    }
    return {
        
        'paymentId': json['paymentId'] == null ? undefined : json['paymentId'],
        'paymentLinkId': json['paymentLinkId'] == null ? undefined : json['paymentLinkId'],
        'paymentLinkReferenceId': json['paymentLinkReferenceId'] == null ? undefined : json['paymentLinkReferenceId'],
        'paymentLinkStatus': json['paymentLinkStatus'] == null ? undefined : json['paymentLinkStatus'],
        'paymentIdZWSP': json['paymentIdZWSP'] == null ? undefined : json['paymentIdZWSP'],
        'status': json['status'] == null ? undefined : json['status'],
    };
}

  export function PaymentDetailsToJSON(json: any): PaymentDetails {
      return PaymentDetailsToJSONTyped(json, false);
  }

  export function PaymentDetailsToJSONTyped(value?: PaymentDetails | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'paymentId': value['paymentId'],
        'paymentLinkId': value['paymentLinkId'],
        'paymentLinkReferenceId': value['paymentLinkReferenceId'],
        'paymentLinkStatus': value['paymentLinkStatus'],
        'paymentIdZWSP': value['paymentIdZWSP'],
        'status': value['status'],
    };
}

