/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PaymentLinkResponse
 */
export interface PaymentLinkResponse {
    /**
     * 
     * @type {string}
     * @memberof PaymentLinkResponse
     */
    paymentLinkUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof PaymentLinkResponse
     */
    paymentLinkId?: string;
}

/**
 * Check if a given object implements the PaymentLinkResponse interface.
 */
export function instanceOfPaymentLinkResponse(value: object): value is PaymentLinkResponse {
    return true;
}

export function PaymentLinkResponseFromJSON(json: any): PaymentLinkResponse {
    return PaymentLinkResponseFromJSONTyped(json, false);
}

export function PaymentLinkResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaymentLinkResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'paymentLinkUrl': json['payment_link_url'] == null ? undefined : json['payment_link_url'],
        'paymentLinkId': json['payment_link_id'] == null ? undefined : json['payment_link_id'],
    };
}

  export function PaymentLinkResponseToJSON(json: any): PaymentLinkResponse {
      return PaymentLinkResponseToJSONTyped(json, false);
  }

  export function PaymentLinkResponseToJSONTyped(value?: PaymentLinkResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'payment_link_url': value['paymentLinkUrl'],
        'payment_link_id': value['paymentLinkId'],
    };
}

