/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { Category } from "./category";
// May contain unused imports in some cases
// @ts-ignore
import type { Seller } from "./seller";

/**
 *
 * @export
 * @interface Product
 */
export interface Product {
  /**
   *
   * @type {number}
   * @memberof Product
   */
  id?: number;
  /**
   *
   * @type {string}
   * @memberof Product
   */
  title?: string;
  /**
   *
   * @type {string}
   * @memberof Product
   */
  description?: string;
  /**
   *
   * @type {number}
   * @memberof Product
   */
  maxPrice?: number;
  /**
   *
   * @type {number}
   * @memberof Product
   */
  quantity?: number;
  /**
   *
   * @type {number}
   * @memberof Product
   */
  sellingPrice?: number;
  /**
   *
   * @type {number}
   * @memberof Product
   */
  discountPercentage?: number;
  /**
   *
   * @type {string}
   * @memberof Product
   */
  color?: string;
  /**
   *
   * @type {Array<string>}
   * @memberof Product
   */
  image?: Array<string>;
  /**
   *
   * @type {number}
   * @memberof Product
   */
  numRatings?: number;
  /**
   *
   * @type {Category}
   * @memberof Product
   */
  category?: Category;
  /**
   *
   * @type {Seller}
   * @memberof Product
   */
  seller?: Seller;
  /**
   *
   * @type {string}
   * @memberof Product
   */
  createdAt?: string;
  /**
   *
   * @type {string}
   * @memberof Product
   */
  updatedAt?: string;
  /**
   *
   * @type {string}
   * @memberof Product
   */
  sizes?: string;
}

