/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Coupon } from './Coupon';
import {
    CouponFromJSON,
    CouponFromJSONTyped,
    CouponToJSON,
    CouponToJSONTyped,
} from './Coupon';

/**
 * 
 * @export
 * @interface ResultCoupon
 */
export interface ResultCoupon {
    /**
     * 
     * @type {boolean}
     * @memberof ResultCoupon
     */
    success?: boolean;
    /**
     * 
     * @type {number}
     * @memberof ResultCoupon
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof ResultCoupon
     */
    message?: string;
    /**
     * 
     * @type {Coupon}
     * @memberof ResultCoupon
     */
    data?: Coupon;
}

/**
 * Check if a given object implements the ResultCoupon interface.
 */
export function instanceOfResultCoupon(value: object): value is ResultCoupon {
    return true;
}

export function ResultCouponFromJSON(json: any): ResultCoupon {
    return ResultCouponFromJSONTyped(json, false);
}

export function ResultCouponFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResultCoupon {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'code': json['code'] == null ? undefined : json['code'],
        'message': json['message'] == null ? undefined : json['message'],
        'data': json['data'] == null ? undefined : CouponFromJSON(json['data']),
    };
}

  export function ResultCouponToJSON(json: any): ResultCoupon {
      return ResultCouponToJSONTyped(json, false);
  }

  export function ResultCouponToJSONTyped(value?: ResultCoupon | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'code': value['code'],
        'message': value['message'],
        'data': CouponToJSON(value['data']),
    };
}

