/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Seller } from './Seller';
import {
    SellerFromJSON,
    SellerFromJSONTyped,
    SellerToJSON,
    SellerToJSONTyped,
} from './Seller';

/**
 * 
 * @export
 * @interface ResultSeller
 */
export interface ResultSeller {
    /**
     * 
     * @type {boolean}
     * @memberof ResultSeller
     */
    success?: boolean;
    /**
     * 
     * @type {number}
     * @memberof ResultSeller
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof ResultSeller
     */
    message?: string;
    /**
     * 
     * @type {Seller}
     * @memberof ResultSeller
     */
    data?: Seller;
}

/**
 * Check if a given object implements the ResultSeller interface.
 */
export function instanceOfResultSeller(value: object): value is ResultSeller {
    return true;
}

export function ResultSellerFromJSON(json: any): ResultSeller {
    return ResultSellerFromJSONTyped(json, false);
}

export function ResultSellerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResultSeller {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'code': json['code'] == null ? undefined : json['code'],
        'message': json['message'] == null ? undefined : json['message'],
        'data': json['data'] == null ? undefined : SellerFromJSON(json['data']),
    };
}

  export function ResultSellerToJSON(json: any): ResultSeller {
      return ResultSellerToJSONTyped(json, false);
  }

  export function ResultSellerToJSONTyped(value?: ResultSeller | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'code': value['code'],
        'message': value['message'],
        'data': SellerToJSON(value['data']),
    };
}

