/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Seller } from './Seller';
import {
    SellerFromJSON,
    SellerFromJSONTyped,
    SellerToJSON,
    SellerToJSONTyped,
} from './Seller';

/**
 * 
 * @export
 * @interface ResultListSeller
 */
export interface ResultListSeller {
    /**
     * 
     * @type {boolean}
     * @memberof ResultListSeller
     */
    success?: boolean;
    /**
     * 
     * @type {number}
     * @memberof ResultListSeller
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof ResultListSeller
     */
    message?: string;
    /**
     * 
     * @type {Array<Seller>}
     * @memberof ResultListSeller
     */
    data?: Array<Seller>;
}

/**
 * Check if a given object implements the ResultListSeller interface.
 */
export function instanceOfResultListSeller(value: object): value is ResultListSeller {
    return true;
}

export function ResultListSellerFromJSON(json: any): ResultListSeller {
    return ResultListSellerFromJSONTyped(json, false);
}

export function ResultListSellerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResultListSeller {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'code': json['code'] == null ? undefined : json['code'],
        'message': json['message'] == null ? undefined : json['message'],
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(SellerFromJSON)),
    };
}

  export function ResultListSellerToJSON(json: any): ResultListSeller {
      return ResultListSellerToJSONTyped(json, false);
  }

  export function ResultListSellerToJSONTyped(value?: ResultListSeller | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'code': value['code'],
        'message': value['message'],
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(SellerToJSON)),
    };
}

