/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Wishlist } from './Wishlist';
import {
    WishlistFromJSON,
    WishlistFromJSONTyped,
    WishlistToJSON,
    WishlistToJSONTyped,
} from './Wishlist';

/**
 * 
 * @export
 * @interface ResultWishlist
 */
export interface ResultWishlist {
    /**
     * 
     * @type {boolean}
     * @memberof ResultWishlist
     */
    success?: boolean;
    /**
     * 
     * @type {number}
     * @memberof ResultWishlist
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof ResultWishlist
     */
    message?: string;
    /**
     * 
     * @type {Wishlist}
     * @memberof ResultWishlist
     */
    data?: Wishlist;
}

/**
 * Check if a given object implements the ResultWishlist interface.
 */
export function instanceOfResultWishlist(value: object): value is ResultWishlist {
    return true;
}

export function ResultWishlistFromJSON(json: any): ResultWishlist {
    return ResultWishlistFromJSONTyped(json, false);
}

export function ResultWishlistFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResultWishlist {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'code': json['code'] == null ? undefined : json['code'],
        'message': json['message'] == null ? undefined : json['message'],
        'data': json['data'] == null ? undefined : WishlistFromJSON(json['data']),
    };
}

  export function ResultWishlistToJSON(json: any): ResultWishlist {
      return ResultWishlistToJSONTyped(json, false);
  }

  export function ResultWishlistToJSONTyped(value?: ResultWishlist | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'code': value['code'],
        'message': value['message'],
        'data': WishlistToJSON(value['data']),
    };
}

