/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Home } from './Home';
import {
    HomeFromJSON,
    HomeFromJSONTyped,
    HomeToJSON,
    HomeToJSONTyped,
} from './Home';

/**
 * 
 * @export
 * @interface ResultHome
 */
export interface ResultHome {
    /**
     * 
     * @type {boolean}
     * @memberof ResultHome
     */
    success?: boolean;
    /**
     * 
     * @type {number}
     * @memberof ResultHome
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof ResultHome
     */
    message?: string;
    /**
     * 
     * @type {Home}
     * @memberof ResultHome
     */
    data?: Home;
}

/**
 * Check if a given object implements the ResultHome interface.
 */
export function instanceOfResultHome(value: object): value is ResultHome {
    return true;
}

export function ResultHomeFromJSON(json: any): ResultHome {
    return ResultHomeFromJSONTyped(json, false);
}

export function ResultHomeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResultHome {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'code': json['code'] == null ? undefined : json['code'],
        'message': json['message'] == null ? undefined : json['message'],
        'data': json['data'] == null ? undefined : HomeFromJSON(json['data']),
    };
}

  export function ResultHomeToJSON(json: any): ResultHome {
      return ResultHomeToJSONTyped(json, false);
  }

  export function ResultHomeToJSONTyped(value?: ResultHome | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'code': value['code'],
        'message': value['message'],
        'data': HomeToJSON(value['data']),
    };
}

