/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Cart } from './Cart';
import {
    CartFromJSON,
    CartFromJSONTyped,
    CartToJSON,
    CartToJSONTyped,
} from './Cart';

/**
 * 
 * @export
 * @interface ResultCart
 */
export interface ResultCart {
    /**
     * 
     * @type {boolean}
     * @memberof ResultCart
     */
    success?: boolean;
    /**
     * 
     * @type {number}
     * @memberof ResultCart
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof ResultCart
     */
    message?: string;
    /**
     * 
     * @type {Cart}
     * @memberof ResultCart
     */
    data?: Cart;
}

/**
 * Check if a given object implements the ResultCart interface.
 */
export function instanceOfResultCart(value: object): value is ResultCart {
    return true;
}

export function ResultCartFromJSON(json: any): ResultCart {
    return ResultCartFromJSONTyped(json, false);
}

export function ResultCartFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResultCart {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'code': json['code'] == null ? undefined : json['code'],
        'message': json['message'] == null ? undefined : json['message'],
        'data': json['data'] == null ? undefined : CartFromJSON(json['data']),
    };
}

  export function ResultCartToJSON(json: any): ResultCart {
      return ResultCartToJSONTyped(json, false);
  }

  export function ResultCartToJSONTyped(value?: ResultCart | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'code': value['code'],
        'message': value['message'],
        'data': CartToJSON(value['data']),
    };
}

