/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Order } from './Order';
import {
    OrderFromJSON,
    OrderFromJSONTyped,
    OrderToJSON,
    OrderToJSONTyped,
} from './Order';

/**
 * 
 * @export
 * @interface ResultOrder
 */
export interface ResultOrder {
    /**
     * 
     * @type {boolean}
     * @memberof ResultOrder
     */
    success?: boolean;
    /**
     * 
     * @type {number}
     * @memberof ResultOrder
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof ResultOrder
     */
    message?: string;
    /**
     * 
     * @type {Order}
     * @memberof ResultOrder
     */
    data?: Order;
}

/**
 * Check if a given object implements the ResultOrder interface.
 */
export function instanceOfResultOrder(value: object): value is ResultOrder {
    return true;
}

export function ResultOrderFromJSON(json: any): ResultOrder {
    return ResultOrderFromJSONTyped(json, false);
}

export function ResultOrderFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResultOrder {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'code': json['code'] == null ? undefined : json['code'],
        'message': json['message'] == null ? undefined : json['message'],
        'data': json['data'] == null ? undefined : OrderFromJSON(json['data']),
    };
}

  export function ResultOrderToJSON(json: any): ResultOrder {
      return ResultOrderToJSONTyped(json, false);
  }

  export function ResultOrderToJSONTyped(value?: ResultOrder | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'code': value['code'],
        'message': value['message'],
        'data': OrderToJSON(value['data']),
    };
}

