/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AuthenticationResponse } from './AuthenticationResponse';
import {
    AuthenticationResponseFromJSON,
    AuthenticationResponseFromJSONTyped,
    AuthenticationResponseToJSON,
    AuthenticationResponseToJSONTyped,
} from './AuthenticationResponse';

/**
 * 
 * @export
 * @interface ResultAuthenticationResponse
 */
export interface ResultAuthenticationResponse {
    /**
     * 
     * @type {boolean}
     * @memberof ResultAuthenticationResponse
     */
    success?: boolean;
    /**
     * 
     * @type {number}
     * @memberof ResultAuthenticationResponse
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof ResultAuthenticationResponse
     */
    message?: string;
    /**
     * 
     * @type {AuthenticationResponse}
     * @memberof ResultAuthenticationResponse
     */
    data?: AuthenticationResponse;
}

/**
 * Check if a given object implements the ResultAuthenticationResponse interface.
 */
export function instanceOfResultAuthenticationResponse(value: object): value is ResultAuthenticationResponse {
    return true;
}

export function ResultAuthenticationResponseFromJSON(json: any): ResultAuthenticationResponse {
    return ResultAuthenticationResponseFromJSONTyped(json, false);
}

export function ResultAuthenticationResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResultAuthenticationResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'code': json['code'] == null ? undefined : json['code'],
        'message': json['message'] == null ? undefined : json['message'],
        'data': json['data'] == null ? undefined : AuthenticationResponseFromJSON(json['data']),
    };
}

  export function ResultAuthenticationResponseToJSON(json: any): ResultAuthenticationResponse {
      return ResultAuthenticationResponseToJSONTyped(json, false);
  }

  export function ResultAuthenticationResponseToJSONTyped(value?: ResultAuthenticationResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'code': value['code'],
        'message': value['message'],
        'data': AuthenticationResponseToJSON(value['data']),
    };
}

