/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { HomeCategory } from './HomeCategory';
import {
    HomeCategoryFromJSON,
    HomeCategoryFromJSONTyped,
    HomeCategoryToJSON,
    HomeCategoryToJSONTyped,
} from './HomeCategory';

/**
 * 
 * @export
 * @interface ResultHomeCategory
 */
export interface ResultHomeCategory {
    /**
     * 
     * @type {boolean}
     * @memberof ResultHomeCategory
     */
    success?: boolean;
    /**
     * 
     * @type {number}
     * @memberof ResultHomeCategory
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof ResultHomeCategory
     */
    message?: string;
    /**
     * 
     * @type {HomeCategory}
     * @memberof ResultHomeCategory
     */
    data?: HomeCategory;
}

/**
 * Check if a given object implements the ResultHomeCategory interface.
 */
export function instanceOfResultHomeCategory(value: object): value is ResultHomeCategory {
    return true;
}

export function ResultHomeCategoryFromJSON(json: any): ResultHomeCategory {
    return ResultHomeCategoryFromJSONTyped(json, false);
}

export function ResultHomeCategoryFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResultHomeCategory {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'code': json['code'] == null ? undefined : json['code'],
        'message': json['message'] == null ? undefined : json['message'],
        'data': json['data'] == null ? undefined : HomeCategoryFromJSON(json['data']),
    };
}

  export function ResultHomeCategoryToJSON(json: any): ResultHomeCategory {
      return ResultHomeCategoryToJSONTyped(json, false);
  }

  export function ResultHomeCategoryToJSONTyped(value?: ResultHomeCategory | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'code': value['code'],
        'message': value['message'],
        'data': HomeCategoryToJSON(value['data']),
    };
}

