/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ResultVoid
 */
export interface ResultVoid {
    /**
     * 
     * @type {boolean}
     * @memberof ResultVoid
     */
    success?: boolean;
    /**
     * 
     * @type {number}
     * @memberof ResultVoid
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof ResultVoid
     */
    message?: string;
    /**
     * 
     * @type {object}
     * @memberof ResultVoid
     */
    data?: object;
}

/**
 * Check if a given object implements the ResultVoid interface.
 */
export function instanceOfResultVoid(value: object): value is ResultVoid {
    return true;
}

export function ResultVoidFromJSON(json: any): ResultVoid {
    return ResultVoidFromJSONTyped(json, false);
}

export function ResultVoidFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResultVoid {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'code': json['code'] == null ? undefined : json['code'],
        'message': json['message'] == null ? undefined : json['message'],
        'data': json['data'] == null ? undefined : json['data'],
    };
}

  export function ResultVoidToJSON(json: any): ResultVoid {
      return ResultVoidToJSONTyped(json, false);
  }

  export function ResultVoidToJSONTyped(value?: ResultVoid | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'code': value['code'],
        'message': value['message'],
        'data': value['data'],
    };
}

