/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AccountDetailDto } from './AccountDetailDto';
import {
    AccountDetailDtoFromJSON,
    AccountDetailDtoFromJSONTyped,
    AccountDetailDtoToJSON,
    AccountDetailDtoToJSONTyped,
} from './AccountDetailDto';

/**
 * 
 * @export
 * @interface ResultListAccountDetailDto
 */
export interface ResultListAccountDetailDto {
    /**
     * 
     * @type {boolean}
     * @memberof ResultListAccountDetailDto
     */
    success?: boolean;
    /**
     * 
     * @type {number}
     * @memberof ResultListAccountDetailDto
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof ResultListAccountDetailDto
     */
    message?: string;
    /**
     * 
     * @type {Array<AccountDetailDto>}
     * @memberof ResultListAccountDetailDto
     */
    data?: Array<AccountDetailDto>;
}

/**
 * Check if a given object implements the ResultListAccountDetailDto interface.
 */
export function instanceOfResultListAccountDetailDto(value: object): value is ResultListAccountDetailDto {
    return true;
}

export function ResultListAccountDetailDtoFromJSON(json: any): ResultListAccountDetailDto {
    return ResultListAccountDetailDtoFromJSONTyped(json, false);
}

export function ResultListAccountDetailDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResultListAccountDetailDto {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'code': json['code'] == null ? undefined : json['code'],
        'message': json['message'] == null ? undefined : json['message'],
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(AccountDetailDtoFromJSON)),
    };
}

  export function ResultListAccountDetailDtoToJSON(json: any): ResultListAccountDetailDto {
      return ResultListAccountDetailDtoToJSONTyped(json, false);
  }

  export function ResultListAccountDetailDtoToJSONTyped(value?: ResultListAccountDetailDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'code': value['code'],
        'message': value['message'],
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(AccountDetailDtoToJSON)),
    };
}

