/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { VerificationCodeReq } from './VerificationCodeReq';
import {
    VerificationCodeReqFromJSON,
    VerificationCodeReqFromJSONTyped,
    VerificationCodeReqToJSON,
    VerificationCodeReqToJSONTyped,
} from './VerificationCodeReq';

/**
 * 
 * @export
 * @interface ResultVerificationCodeReq
 */
export interface ResultVerificationCodeReq {
    /**
     * 
     * @type {boolean}
     * @memberof ResultVerificationCodeReq
     */
    success?: boolean;
    /**
     * 
     * @type {number}
     * @memberof ResultVerificationCodeReq
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof ResultVerificationCodeReq
     */
    message?: string;
    /**
     * 
     * @type {VerificationCodeReq}
     * @memberof ResultVerificationCodeReq
     */
    data?: VerificationCodeReq;
}

/**
 * Check if a given object implements the ResultVerificationCodeReq interface.
 */
export function instanceOfResultVerificationCodeReq(value: object): value is ResultVerificationCodeReq {
    return true;
}

export function ResultVerificationCodeReqFromJSON(json: any): ResultVerificationCodeReq {
    return ResultVerificationCodeReqFromJSONTyped(json, false);
}

export function ResultVerificationCodeReqFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResultVerificationCodeReq {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'code': json['code'] == null ? undefined : json['code'],
        'message': json['message'] == null ? undefined : json['message'],
        'data': json['data'] == null ? undefined : VerificationCodeReqFromJSON(json['data']),
    };
}

  export function ResultVerificationCodeReqToJSON(json: any): ResultVerificationCodeReq {
      return ResultVerificationCodeReqToJSONTyped(json, false);
  }

  export function ResultVerificationCodeReqToJSONTyped(value?: ResultVerificationCodeReq | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'code': value['code'],
        'message': value['message'],
        'data': VerificationCodeReqToJSON(value['data']),
    };
}

