/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AccountDetailDto } from './AccountDetailDto';
import {
    AccountDetailDtoFromJSON,
    AccountDetailDtoFromJSONTyped,
    AccountDetailDtoToJSON,
    AccountDetailDtoToJSONTyped,
} from './AccountDetailDto';

/**
 * 
 * @export
 * @interface ResultAccountDetailDto
 */
export interface ResultAccountDetailDto {
    /**
     * 
     * @type {boolean}
     * @memberof ResultAccountDetailDto
     */
    success?: boolean;
    /**
     * 
     * @type {number}
     * @memberof ResultAccountDetailDto
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof ResultAccountDetailDto
     */
    message?: string;
    /**
     * 
     * @type {AccountDetailDto}
     * @memberof ResultAccountDetailDto
     */
    data?: AccountDetailDto;
}

/**
 * Check if a given object implements the ResultAccountDetailDto interface.
 */
export function instanceOfResultAccountDetailDto(value: object): value is ResultAccountDetailDto {
    return true;
}

export function ResultAccountDetailDtoFromJSON(json: any): ResultAccountDetailDto {
    return ResultAccountDetailDtoFromJSONTyped(json, false);
}

export function ResultAccountDetailDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResultAccountDetailDto {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'code': json['code'] == null ? undefined : json['code'],
        'message': json['message'] == null ? undefined : json['message'],
        'data': json['data'] == null ? undefined : AccountDetailDtoFromJSON(json['data']),
    };
}

  export function ResultAccountDetailDtoToJSON(json: any): ResultAccountDetailDto {
      return ResultAccountDetailDtoToJSONTyped(json, false);
  }

  export function ResultAccountDetailDtoToJSONTyped(value?: ResultAccountDetailDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'code': value['code'],
        'message': value['message'],
        'data': AccountDetailDtoToJSON(value['data']),
    };
}

