/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Product } from './Product';
import {
    ProductFromJSON,
    ProductFromJSONTyped,
    ProductToJSON,
    ProductToJSONTyped,
} from './Product';

/**
 * 
 * @export
 * @interface ResultProduct
 */
export interface ResultProduct {
    /**
     * 
     * @type {boolean}
     * @memberof ResultProduct
     */
    success?: boolean;
    /**
     * 
     * @type {number}
     * @memberof ResultProduct
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof ResultProduct
     */
    message?: string;
    /**
     * 
     * @type {Product}
     * @memberof ResultProduct
     */
    data?: Product;
}

/**
 * Check if a given object implements the ResultProduct interface.
 */
export function instanceOfResultProduct(value: object): value is ResultProduct {
    return true;
}

export function ResultProductFromJSON(json: any): ResultProduct {
    return ResultProductFromJSONTyped(json, false);
}

export function ResultProductFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResultProduct {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'code': json['code'] == null ? undefined : json['code'],
        'message': json['message'] == null ? undefined : json['message'],
        'data': json['data'] == null ? undefined : ProductFromJSON(json['data']),
    };
}

  export function ResultProductToJSON(json: any): ResultProduct {
      return ResultProductToJSONTyped(json, false);
  }

  export function ResultProductToJSONTyped(value?: ResultProduct | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'code': value['code'],
        'message': value['message'],
        'data': ProductToJSON(value['data']),
    };
}

