/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SellerReport } from './SellerReport';
import {
    SellerReportFromJSON,
    SellerReportFromJSONTyped,
    SellerReportToJSON,
    SellerReportToJSONTyped,
} from './SellerReport';

/**
 * 
 * @export
 * @interface ResultSellerReport
 */
export interface ResultSellerReport {
    /**
     * 
     * @type {boolean}
     * @memberof ResultSellerReport
     */
    success?: boolean;
    /**
     * 
     * @type {number}
     * @memberof ResultSellerReport
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof ResultSellerReport
     */
    message?: string;
    /**
     * 
     * @type {SellerReport}
     * @memberof ResultSellerReport
     */
    data?: SellerReport;
}

/**
 * Check if a given object implements the ResultSellerReport interface.
 */
export function instanceOfResultSellerReport(value: object): value is ResultSellerReport {
    return true;
}

export function ResultSellerReportFromJSON(json: any): ResultSellerReport {
    return ResultSellerReportFromJSONTyped(json, false);
}

export function ResultSellerReportFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResultSellerReport {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'code': json['code'] == null ? undefined : json['code'],
        'message': json['message'] == null ? undefined : json['message'],
        'data': json['data'] == null ? undefined : SellerReportFromJSON(json['data']),
    };
}

  export function ResultSellerReportToJSON(json: any): ResultSellerReport {
      return ResultSellerReportToJSONTyped(json, false);
  }

  export function ResultSellerReportToJSONTyped(value?: ResultSellerReport | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'code': value['code'],
        'message': value['message'],
        'data': SellerReportToJSON(value['data']),
    };
}

