/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CartItem } from './CartItem';
import {
    CartItemFromJSON,
    CartItemFromJSONTyped,
    CartItemToJSON,
    CartItemToJSONTyped,
} from './CartItem';

/**
 * 
 * @export
 * @interface ResultCartItem
 */
export interface ResultCartItem {
    /**
     * 
     * @type {boolean}
     * @memberof ResultCartItem
     */
    success?: boolean;
    /**
     * 
     * @type {number}
     * @memberof ResultCartItem
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof ResultCartItem
     */
    message?: string;
    /**
     * 
     * @type {CartItem}
     * @memberof ResultCartItem
     */
    data?: CartItem;
}

/**
 * Check if a given object implements the ResultCartItem interface.
 */
export function instanceOfResultCartItem(value: object): value is ResultCartItem {
    return true;
}

export function ResultCartItemFromJSON(json: any): ResultCartItem {
    return ResultCartItemFromJSONTyped(json, false);
}

export function ResultCartItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResultCartItem {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'code': json['code'] == null ? undefined : json['code'],
        'message': json['message'] == null ? undefined : json['message'],
        'data': json['data'] == null ? undefined : CartItemFromJSON(json['data']),
    };
}

  export function ResultCartItemToJSON(json: any): ResultCartItem {
      return ResultCartItemToJSONTyped(json, false);
  }

  export function ResultCartItemToJSONTyped(value?: ResultCartItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'code': value['code'],
        'message': value['message'],
        'data': CartItemToJSON(value['data']),
    };
}

