/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Deal } from './Deal';
import {
    DealFromJSON,
    DealFromJSONTyped,
    DealToJSON,
    DealToJSONTyped,
} from './Deal';

/**
 * 
 * @export
 * @interface ResultDeal
 */
export interface ResultDeal {
    /**
     * 
     * @type {boolean}
     * @memberof ResultDeal
     */
    success?: boolean;
    /**
     * 
     * @type {number}
     * @memberof ResultDeal
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof ResultDeal
     */
    message?: string;
    /**
     * 
     * @type {Deal}
     * @memberof ResultDeal
     */
    data?: Deal;
}

/**
 * Check if a given object implements the ResultDeal interface.
 */
export function instanceOfResultDeal(value: object): value is ResultDeal {
    return true;
}

export function ResultDealFromJSON(json: any): ResultDeal {
    return ResultDealFromJSONTyped(json, false);
}

export function ResultDealFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResultDeal {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'code': json['code'] == null ? undefined : json['code'],
        'message': json['message'] == null ? undefined : json['message'],
        'data': json['data'] == null ? undefined : DealFromJSON(json['data']),
    };
}

  export function ResultDealToJSON(json: any): ResultDeal {
      return ResultDealToJSONTyped(json, false);
  }

  export function ResultDealToJSONTyped(value?: ResultDeal | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'code': value['code'],
        'message': value['message'],
        'data': DealToJSON(value['data']),
    };
}

