/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Product } from './Product';
import {
    ProductFromJSON,
    ProductFromJSONTyped,
    ProductToJSON,
    ProductToJSONTyped,
} from './Product';

/**
 * 
 * @export
 * @interface ResultListProduct
 */
export interface ResultListProduct {
    /**
     * 
     * @type {boolean}
     * @memberof ResultListProduct
     */
    success?: boolean;
    /**
     * 
     * @type {number}
     * @memberof ResultListProduct
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof ResultListProduct
     */
    message?: string;
    /**
     * 
     * @type {Array<Product>}
     * @memberof ResultListProduct
     */
    data?: Array<Product>;
}

/**
 * Check if a given object implements the ResultListProduct interface.
 */
export function instanceOfResultListProduct(value: object): value is ResultListProduct {
    return true;
}

export function ResultListProductFromJSON(json: any): ResultListProduct {
    return ResultListProductFromJSONTyped(json, false);
}

export function ResultListProductFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResultListProduct {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'code': json['code'] == null ? undefined : json['code'],
        'message': json['message'] == null ? undefined : json['message'],
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(ProductFromJSON)),
    };
}

  export function ResultListProductToJSON(json: any): ResultListProduct {
      return ResultListProductToJSONTyped(json, false);
  }

  export function ResultListProductToJSONTyped(value?: ResultListProduct | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'code': value['code'],
        'message': value['message'],
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(ProductToJSON)),
    };
}

