/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { User } from './user';

/**
 * 
 * @export
 * @interface Review
 */
export interface Review {
    /**
     * 
     * @type {number}
     * @memberof Review
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof Review
     */
    'reviewText'?: string;
    /**
     * 
     * @type {number}
     * @memberof Review
     */
    'rating'?: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof Review
     */
    'productImages'?: Array<string>;
    /**
     * 
     * @type {User}
     * @memberof Review
     */
    'user': User;
    /**
     * 
     * @type {string}
     * @memberof Review
     */
    'createdAt'?: string;
}

