/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Seller } from './seller';

/**
 * 
 * @export
 * @interface SellerReport
 */
export interface SellerReport {
    /**
     * 
     * @type {number}
     * @memberof SellerReport
     */
    'id'?: number;
    /**
     * 
     * @type {Seller}
     * @memberof SellerReport
     */
    'seller'?: Seller;
    /**
     * 
     * @type {number}
     * @memberof SellerReport
     */
    'totalEarnings'?: number;
    /**
     * 
     * @type {number}
     * @memberof SellerReport
     */
    'totalSales'?: number;
    /**
     * 
     * @type {number}
     * @memberof SellerReport
     */
    'totalRefunds'?: number;
    /**
     * 
     * @type {number}
     * @memberof SellerReport
     */
    'totalTax'?: number;
    /**
     * 
     * @type {number}
     * @memberof SellerReport
     */
    'netEarnings'?: number;
    /**
     * 
     * @type {number}
     * @memberof SellerReport
     */
    'totalOrders'?: number;
    /**
     * 
     * @type {number}
     * @memberof SellerReport
     */
    'canceledOrders'?: number;
    /**
     * 
     * @type {number}
     * @memberof SellerReport
     */
    'totalTransactions'?: number;
}

