/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { User } from './User';
import {
    UserFromJSON,
    UserFromJSONTyped,
    UserToJSON,
    UserToJSONTyped,
} from './User';
import type { Seller } from './Seller';
import {
    SellerFromJSON,
    SellerFromJSONTyped,
    SellerToJSON,
    SellerToJSONTyped,
} from './Seller';

/**
 * 
 * @export
 * @interface VerificationCode
 */
export interface VerificationCode {
    /**
     * 
     * @type {number}
     * @memberof VerificationCode
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof VerificationCode
     */
    otp?: string;
    /**
     * 
     * @type {string}
     * @memberof VerificationCode
     */
    email?: string;
    /**
     * 
     * @type {User}
     * @memberof VerificationCode
     */
    user?: User;
    /**
     * 
     * @type {Seller}
     * @memberof VerificationCode
     */
    seller?: Seller;
}

/**
 * Check if a given object implements the VerificationCode interface.
 */
export function instanceOfVerificationCode(value: object): value is VerificationCode {
    return true;
}

export function VerificationCodeFromJSON(json: any): VerificationCode {
    return VerificationCodeFromJSONTyped(json, false);
}

export function VerificationCodeFromJSONTyped(json: any, ignoreDiscriminator: boolean): VerificationCode {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'otp': json['otp'] == null ? undefined : json['otp'],
        'email': json['email'] == null ? undefined : json['email'],
        'user': json['user'] == null ? undefined : UserFromJSON(json['user']),
        'seller': json['seller'] == null ? undefined : SellerFromJSON(json['seller']),
    };
}

  export function VerificationCodeToJSON(json: any): VerificationCode {
      return VerificationCodeToJSONTyped(json, false);
  }

  export function VerificationCodeToJSONTyped(value?: VerificationCode | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'otp': value['otp'],
        'email': value['email'],
        'user': UserToJSON(value['user']),
        'seller': SellerToJSON(value['seller']),
    };
}

