/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Seller } from './seller';
// May contain unused imports in some cases
// @ts-ignore
import type { User } from './user';

/**
 * 
 * @export
 * @interface VerificationCode
 */
export interface VerificationCode {
    /**
     * 
     * @type {number}
     * @memberof VerificationCode
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof VerificationCode
     */
    'otp'?: string;
    /**
     * 
     * @type {string}
     * @memberof VerificationCode
     */
    'email'?: string;
    /**
     * 
     * @type {User}
     * @memberof VerificationCode
     */
    'user'?: User;
    /**
     * 
     * @type {Seller}
     * @memberof VerificationCode
     */
    'seller'?: Seller;
}

